name: stack-wrapper
version: 0.1.0
github: "kakkun61/stack-wrapper"
license: BSD3
author: "Kazuki Okamoto"
maintainer: "kazuki.okamoto@kakkun61.com"
copyright: "Kazuki Okamoto"

extra-source-files:
- README.md
- ChangeLog.md

description: Please see the README on GitHub at <https://github.com/kakkun61/stack-wrapper#readme>

dependencies:
- base >= 4.7
- process >= 1.2

when:
- condition: os(windows)
  dependencies:
  - filepath

library:
  source-dirs: src
 
executables:
  ghc:
    main: ghc.hs
    source-dirs: app
    dependencies:
    - stack-wrapper

  exe:
    main: exe.hs
    source-dirs: app
    dependencies:
    - stack-wrapper
