name: stack-wrapper
version: 0.1.0
github: "kakkun61/stack-wrapper"
license: BSD3
author: "Kazuki Okamoto"
maintainer: "kazuki.okamoto@kakkun61.com"
copyright: "Kazuki Okamoto"
category: Development
synopsis: Call ghc within stack by calling ghc
description: When you invoke ghc of stack-wrapper, you can invoke the appropriate one which specified by the resolver of stack.yaml.

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7
- filepath >= 1.4
- process >= 1.2

ghc-options:
- -Wall
- -Wcompat

library:
  source-dirs: src
 
executables:
  ghc:
    main: ghc.hs
    source-dirs: app
    dependencies:
    - stack-wrapper

  ghc-pkg:
    main: ghc-pkg.hs
    source-dirs: app
    dependencies:
    - stack-wrapper

  ghci:
    main: ghci.hs
    source-dirs: app
    dependencies:
    - stack-wrapper

  haddock:
    main: haddock.hs
    source-dirs: app
    dependencies:
    - stack-wrapper

  hp2ps:
    main: hp2ps.hs
    source-dirs: app
    dependencies:
    - stack-wrapper

  hsc2hs:
    main: hsc2hs.hs
    source-dirs: app
    dependencies:
    - stack-wrapper

  runghc:
    main: runghc.hs
    source-dirs: app
    dependencies:
    - stack-wrapper

  runhaskell:
    main: runhaskell.hs
    source-dirs: app
    dependencies:
    - stack-wrapper

  exe:
    main: exe.hs
    source-dirs: app
    dependencies:
    - stack-wrapper
